static char *ENEMIES[] = 
{
    "Storyline",
    "Encounter",
    "Serpentis",
    "Amarr Empire",
    "Rogue Drones",
    "Blood Raiders",
    "Guristas",
    "Minmatar Republic",
    "Gallente Federation",
    "Ammatar Mandate",
    "Angel Cartel",
    "Guristas Pirates",
    "Sansha's Nation",
    "Rogue Pirates",
    "DED",
    "Khanid Kingdom",
    "Caldari State",
    "Mordu's Legion",
    "Mercenaries",
    "Thukker Tribe",
    "CONCORD",
    "Deadspace Droneswarm",
};
