static char *ITEMS[] = {
    
"Tritanium",
"Integrated Berserker",
"Packrat Mobile Tractor Unit",
"10M Bounty SCC Encrypted Bond",
"125mm Light Scout Autocannon I",
"18th Tier Overseers Personal Effects",
"1MN Y-S8 Compact Afterburner",
"21st Tier Overseers Personal Effects",
"Pilots License Extension (PLEX)",
"8th Tier Overseers Personal Effects",
"Agency Overclocker SB9 Dose IV",
"Algos",
"Anode Mega Electron Particle Cannon I",
"Antimatter Charge M",
"Antimatter Charge S",
"Aqueous Liquids",
"Arkonor",
"Atmospheric Gases",
"Atron",
"Attainment Decryptor",
"Augmentation Decryptor",
"Augoror",
"Autotrophs",
"Azure Plagioclase",
"Azure Plagioclase",
"Bacteria",
"Bacteria",
"Badger",
"Barrage M",
"Barren Command Center",
"Base Metals",
"Biocells",
"Biofuels",
"Biomass",
"Bistot",
"Blackbird",
"Blood Ultraviolet S",
"Bomb Launcher II",
"Brimful Sylvite",
"Brimful Zeolites",
"Broken Drone Transceiver",
"Caldari Navy Captain Insignia II",
"Caldari Navy Hookbill",
"Caldari Navy Inferno Light Missile",
"Caldari Navy Mjolnir Cruise Missile",
"Caldari Navy Scourge Light Missile",
"Cap Booster 400",
"Cap Recharger II",
"Capital Energy Turret",
"Caracal",
"Carbon Compounds",
"Catalyst",
"Chiral Structures",
"Chiral Structures",
"Co-Processor II",
"Coercer",
"Compact Entropic Radiation Sink",
"Compact Explosive Shield Hardener",
"Complex Organisms",
"Compressed Concentrated Veldspar",
"Compressed Dense Veldspar",
"Compressed Glacial Mass",
"Compressed Gneiss",
"Compressed Massive Scordite",
"Compressed Pyroxeres",
"Compressed Scordite",
"Compressed Veldspar",
"Concentrated Veldspar",
"Concentrated Veldspar",
"Condensates",
"Condensed Scordite",
"Confessor",
"Contaminated Lorentz Fluid",
"Coolant",
"Corax",
"Core Probe Launcher II",
"Cormorant Navy Issue",
"Covert Ops Cloaking Device II",
"Crane",
"Crimson Arkonor",
"Crokite",
"Crow",
"Crucifier",
"Crystalline Carbonide",
"Crystalline Crokite",
"Cybernetic Subprocessor - Standard",
"Dark Ochre",
"Datacore - Nuclear Physics",
"Datacore - Plasma Physics",
"Defective Current Pump",
"Dense Veldspar",
"Dense Veldspar",
"Dragoon",
"Drake Navy Issue",
"Drone Coronary Unit",
"Drone Navigation Computer I",
"Echelon",
"Electrolytes",
"Electrolytes",
"Electromechanical Hull Sheeting",
"Enormous Freight Container",
"Enriched Uranium",
"Evaporite Deposits",
"Executioner",
"Explosive Shield Hardener II",
"Federation Navy Hobgoblin",
"Felsic Magma",
"Fermionic Condensates",
"Fernite Carbide",
"Fierce Exotic Filament",
"Fierce Gamma Filament",
"Fiery Kernite",
"Fullerides",
"Fullerite-C60",
"Fullerite-C70",
"Fullerite-C84",
"Gas Cloud Scoop I",
"Gel-Matrix Biopaste",
"Gila",
"Gistum B-Type 50MN Microwarpdrive",
"Glistening Bitumens",
"Gneiss",
"Gnosis",
"Golden Omber",
"Griffin",
"Guardian",
"Hammerhead II",
"Heavy Gunnar Compact Stasis Grappler",
"Heavy Metals",
"Heavy Water",
"Hedbergite",
"Helios",
"Helium Isotopes",
"Hemorphite",
"Hornet EC-300",
"Hurricane",
"Hydrogen Isotopes",
"Imicus",
"Imperial Navy Sergeant Insignia II",
"Improved Cloaking Device II",
"Incursus",
"Industrial Fibers",
"Interdiction Sphere Launcher I",
"Ionic Solutions",
"Iridium Charge S",
"Iron Charge S",
"Ishkur",
"Isogen",
"Jaspet",
"Kernite",
"Khumaak",
"Kryos",
"Large Explosive Armor Reinforcer I",
"Large Rudimentary Concussion Bomb I",
"Large Standard Container",
"Lead Charge S",
"Liquid Ozone",
"Liquid Ozone",
"Livestock",
"Lorentz Fluid",
"Luminous Kernite",
"Massive Scordite",
"Megacyte",
"Megacyte",
"Mercoxit",
"Merlin",
"Mexallon",
"Microorganisms",
"Minmatar Shuttle",
"Mjolnir Precision Cruise Missile",
"Moa",
"Mobile Large Warp Disruptor I",
"Monoclinic Bistot",
"Morphite",
"Muninn",
"Navy Cap Booster 25",
"Nereus",
"Nitrogen Isotopes",
"Noble Gas",
"Noble Metals",
"Nocxium",
"Non-CS Crystals",
"Nonlinear Metamaterials",
"Nova Javelin Torpedo",
"Null S",
"Obelisk",
"Ogre I",
"Omber",
"Omen Navy Issue",
"Optimized Augmentation Decryptor",
"Organic Mortar Applicators",
"Osprey",
"Oxides",
"Oxidizing Compound",
"Oxidizing Compound",
"Oxygen",
"Oxygen Isotopes",
"Oxygen Isotopes",
"Pilgrim",
"Pith X-Type Explosive Shield Hardener",
"Plagioclase",
"Planktic Colonies",
"Plasmoids",
"Plasmoids",
"Praetor I",
"Precious Metals",
"Precious Metals",
"Prime Arkonor",
"Pristine Jaspet",
"Procurer",
"Prorator",
"Proteins",
"Prototype Cloaking Device I",
"Prototype Compact EM Armor Hardener",
"Purifier",
"Pyerite",
"Pyroxeres",
"Pyroxeres",
"Quafe Zero Classic",
"Raging Dark Filament",
"Rapier",
"Rattlesnake",
"Reactive Gas",
"Reactive Metals",
"Recursive Computing Module",
"Reports",
"Republic Fleet Firetail",
"Rich Plagioclase",
"Robotics",
"Scordite",
"Scourge Rage Heavy Assault Missile",
"Sigil",
"Silicates",
"Silicon",
"Silicon",
"Silvery Omber",
"Skill Injector",
"Slasher",
"Slaves",
"Small Arms",
"Small Artillery Battery",
"Small Tractor Beam II",
"Solid Pyroxeres",
"Spike L",
"Spodumain",
"Stabber",
"Standup Manufacturing Plant I",
"Standup Stasis Webifier I",
"Station Vault Container",
"Station Warehouse Container",
"Strip Miner I",
"Strontium Clathrates",
"Superconductor Rails",
"Suspended Plasma",
"Svipul",
"Sylramic Fibers",
"Synthetic Oil",
"Synthetic Oil",
"Ta3 Compact Ship Scanner",
"Talos",
"Talwar",
"Tangled Power Conduit",
"Terahertz Metamaterials",
"Tesseract Capacitor Unit",
"Test Cultures",
"Thanatos",
"Thorax",
"Thrasher",
"Titanium Carbide",
"Toxic Metals",
"Toxic Metals",
"Tracking Disruptor II",
"Triclinic Bistot",
"Trigger Unit",
"True Sansha Power Diagnostic System",
"Tungsten Carbide",
"Tungsten Charge L",
"Velator",
"Veldspar",
"Venture",
"Vexor",
"Viator",
"Vigil",
"Viscous Pyroxeres",
"Void M",
"Void S",
"Wasp I",
"Water",
"Wheat",
"White Glaze",
"Worm",
"Wreathe",
"Wrecked Hull Section",
"Zero-Point Condensate",
"Zydrine"
};