
static char *MISSIONS[] = 
{
"A Watchful Eye",
"After The Seven",
"Against The Empire",
"Air Show!",
"Alluring Emanations",
"Amarr Excavators",
"Amarrian Tyrants",
"Ambush the Convoy",
"Ambush the Personnel Transport",
"Ambushed Ally",
"Ammatar Detective Spotted",
"Ammatar Scouts Spotted",
"An Advantageous Catastrophe",
"An Ancient Roster",
"The Angel Cartel Spies",
"Angel Extravaganza",
"Angel Strike",
"The Anomaly",
"Another Slave Rescue",
"Are You Receiving?",
"Artifact Recovery",
"The Assault",
"Athran Exigency",
"Attack of the Drones",
"Attack the Angel Hideout",
"Augumene Allergen",
"Avenge a Fallen Comrade",
"The Big Sting",
"The Black Market Hub",
"The Blockade",
"The Blood of Angry Men",
"Blood Farm",
"The Blood Raider Spies",
"Break The Slave Trade",
"Break Their Will",
"Breeding Facility",
"Buzz Kill",
"Caldari Beacons",
"Cargo Delivery",
"Carrying AIMED's",
"A Case of Kidnapping",
"Chain Reaction",
"Cleaning House",
"Cleansing Fire",
"Clear the Traderoute",
"Clearing a Path",
"Closing the Gate",
"Codename 'Redress'",
"Communications Cold War",
"CONCORD Scout Spotted",
"Convoy Attack",
"Corporate Records",
"The Cost of Greener Grass",
"Covering your Tracks",
"Crooked Cop",
"Crowd Control",
"Crush The Sebiestor Station",
"Crystal Dreams Shattered",
"Customs Interdiction",
"Cut","Throat Competition",
"The Damsel in Distress",
"Dark Alliance",
"Data Mining",
"Dead Drift",
"Deadly Arrival",
"Deadly Serious",
"Delving Into the Past",
"Denial Of Reconnaissance",
"Desperate Maneuvers",
"Desperate Measures",
"Destroy the Ammatar Base",
"Destroy the Caldari Outpost",
"Diplomatic Incident",
"Dirty Job",
"The Disgruntled Employee",
"Dissidents",
"Down with the Legion",
"Dread Pirate Scarlet",
"Driving a Wedge",
"Drone Detritus",
"Drone Infestation",
"Drug Bust",
"Duo of Death",
"Eliminate a Pirate Nuisance",
"Eliminate the Pirate Campers",
"Eliminate the Stargate Campers",
"Elopement",
"Encounter at Station",
"An End to Eavesdropping",
"Endless Battle","Tutorial",
"Enemies Abound",
"Escaped Dissident",
"Escaped Killer",
"Escaped Spy",
"Escaped Terrorist",
"Evolution",
"Exploited Sensitivities",
"Extract The Renegade",
"Fair Play",
"Fate of Angels",
"Father And Son",
"Federal Confidence",
"Feeding Frenzy",
"Fetching Friends",
"Finders And Keepers",
"Flame of Peace",
"Foil The Military Preparations",
"For Justice",
"For the Birds",
"For the Honor of Rouvenor",
"Forbidden Cloning",
"A Force to be Reckoned with",
"Forces Amassing",
"Foreign Investment",
"Forgotten Outpost",
"The Fortress",
"The Fox Hunt",
"Freedom And Commerce",
"Freedom Must Not Prevail",
"Freeing the Informant",
"Friendly Spies",
"Furrier Fiasco",
"Gallente Detective Spotted",
"Gallente Scouts Spotted",
"Gate Blitz",
"Gate to Nowhere",
"Get the Relic",
"Gone Berserk","EoM",
"The Good Word",
"Scions of the Superior Gene",
"Guristas Extravaganza",
"The Guristas Spies",
"Guristas Strike",
"Halt the Invasion",
"The Hard Way",
"Head Hunter Threat",
"The Heir's Favorite Slave",
"Hidden Enemy Base",
"Hidden Hope",
"The Hidden Stash",
"Honor",
"Human Cattle",
"Humble Beginnings",
"Illegal Activity",
"Imperial Scouts Spotted",
"In The Midst of Deadspace",
"In The Shadow Of War",
"The Infested Ruins",
"Infiltrated Outposts",
"Informed Attack",
"Innocents In The Crossfire",
"Insorum Hijacking","Minmatar",
"Inspired",
"Intaki and Mordus Legion",
"Intercept The Pirate Smugglers",
"Intercept The Saboteurs",
"Interstellar Railroad",
"Jealous Rivals",
"Khanid Nobleman",
"Kidnappers Strike",
"The Kidnapping",
"Labor of Love",
"Labors of War",
"Lamb Amongst Lions",
"Lasers Softly Beaming",
"Letters from Dalamaid",
"The Left Hook",
"Liberate the Miners",
"Lights Out",
"Location Location",
"Lost Records",
"Lost That Bet",
"Mannar Mining Colony",
"Mass Drivers",
"Massive Attack",
"Matriarch",
"Million Little Pieces",
"Mining Misappropriation",
"Minmatar Plot",
"The Missing Convoy",
"Missing Persons Report",
"Missing Reporters",
"Mission of Mercy",
"Morale and Morality",
"The Mordus Headhunters",
"Mordu's Folly",
"A Mote In The Eye",
"The Mouthy Merc",
"Murderer Brought to Justice",
"My Sweet Privateer",
"Mysterious Sightings",
"Navy Armada",
"New Frontiers",
"Nine Tenths Of The Wormhole",
"No Excuse",
"No Honor",
"Onslaught",
"Opening Moves",
"Operation Hamstring",
"Operation Wyrmsbane",
"Operation Wyrmslayer",
"Oust The Claimjumpers",
"Patient Zero",
"Patriotic Measures",
"Persistent Enemy",
"Pick Your Poison",
"Pirate Aggression",
"Pirate Business",
"Pirate Intrusion",
"Pirate Invasion",
"Pirate Nuisance",
"Pirate Radio",
"Pirate Slaughter",
"Police Intrusion",
"Police Invasion",
"Postmodern Primitives",
"Pot and Kettle",
"Portal to War",
"Preaching to the Masses",
"Preliminary Strike",
"Prison Break",
"Prison Bust",
"Prison Transfer",
"Probing Question",
"Propaganda War",
"Quota Season",
"Racetrack Ruckus",
"Reclamation",
"Recon",
"Record Cleaning",
"Recover the Containers",
"Retribution",
"Revenge Attack",
"The Right Hand of Zazzmatazz",
"Ritualist Raids",
"Rogue Drone Harassment",
"Rogue Eradication",
"Rogue Hunt",
"The Rogue Slave Trader",
"Rogue Spy",
"Rogue Tech",
"Roid Rage",
"Roving Rogue Drones",
"Sansha Acquisition",
"Sansha on the Horizon",
"The Sansha Spies",
"Save a Man's Career",
"Save the Miners",
"Scavengers",
"The Score",
"Scout It Out",
"Search and Rescue",
"Secret Pickup",
"Secret Project X",
"Seek and Destroy",
"Serpent And The Slaves",
"Serpentis Extravaganza",
"Serpentis Ship Builders",
"The Serpentis Spies",
"The Seven's Brothel",
"The Seven's Prison Facility",
"Shades of Grey",
"Shaman Secrets",
"Shipyard Theft",
"Silence Deep as Death",
"Silence the Informant",
"The Slaves Must Be Returned",
"The Small Armory",
"Small Misunderstanding",
"Smash The Gallente Stockyard",
"Smash The Supplier",
"Smash The Shipyard",
"Smuggler Interception",
"Soft Drink Wars",
"Soothe The Salvage Beast",
"The Space Telescope",
"The Spy Stash",
"The Spy Stash",
"Stem The Flow",
"Stray Amarr Carrier",
"Stray Caldari Carrier",
"Stop the Thief",
"Success Comes At A Price",
"Suntendi Recall",
"Surprise Surprise",
"Survey Rendezvous",
"Listening Post",
"Kicking the Nest",
"Technological Secrets",
"Terrorism!",
"They Robots",
"Tomb Of The Unknown Soldiers",
"Threat from Afar",
"Transport Duty",
"Trespassers",
"Trimming The Fat",
"Troop Build Up",
"Unauthorized Military Presence",
"Under Suspicion",
"Undue Attention",
"The Uprising",
"Vengeance",
"Violent Expulsion",
"The Voting Trail",
"War Situation",
"Warlord Strikes",
"What Comes Around Goes Around",
"What Slavery Begets",
"What's In a Name",
"Whispers In The Dark",
"The Wildcat Strike",
"A Wolf by the Ears",
"Worlds Collide",
"Wrath of Angels"
};