static char *SKILLS[] = 
{
"Gunnery",
"Small Hybrid Turret",
"Small Projectile Turret",
"Small Energy Turret",
"Medium Hybrid Turret",
"Medium Projectile Turret",
"Medium Energy Turret",
"Large Hybrid Turret",
"Large Projectile Turret",
"Large Energy Turret",
"Rapid Firing",
"Sharpshooter",
"Motion Prediction",
"Surgical Strike",
"Controlled Bursts",
"Trajectory Analysis",
"Capital Energy Turret",
"Capital Hybrid Turret",
"Capital Projectile Turret",
"Doomsday Operation",
"Doomsday Rapid Firing",
"Small Precursor Weapon",
"Medium Precursor Weapon",
"Large Precursor Weapon",
"Capital Precursor Weapon",
"Large Vorton Projector",
"Vorton Power Amplification",
"Vorton Arc Guidance",
"Vorton Projector Operation",
"Small Vorton Projector",
"Medium Vorton Projector",
"Vorton Arc Extension",
"Missile Launcher Operation",
"Rockets",
"Light Missiles",
"Auto-Targeting Missiles",
"Defender Missiles",
"Heavy Missiles",
"Torpedoes",
"Cruise Missiles",
"Missile Bombardment",
"Missile Projection",
"Guided Missile Precision",
"Target Navigation Prediction",
"Warhead Upgrades",
"Rapid Launch",
"XL Torpedoes",
"Heavy Assault Missiles",
"Bomb Deployment",
"XL Cruise Missiles",
"ORE Hauler",
"Spaceship Command",
"Gallente Frigate",
"Minmatar Frigate",
"Caldari Frigate",
"Amarr Frigate",
"Gallente Cruiser",
"Minmatar Cruiser",
"Caldari Cruiser",
"Amarr Cruiser",
"Gallente Battleship",
"Minmatar Battleship",
"Caldari Battleship",
"Amarr Battleship",
"Gallente Hauler",
"Minmatar Hauler",
"Caldari Hauler",
"Amarr Hauler",
"Gallente Titan",
"Minmatar Titan",
"Caldari Titan",
"Amarr Titan",
"Interceptors",
"Covert Ops",
"Assault Frigates",
"Logistics Cruisers",
"Interdictors",
"Heavy Assault Cruisers",
"Mining Barge",
"Transport Ships",
"Advanced Spaceship Command",
"Amarr Freighter",
"Amarr Dreadnought",
"Caldari Freighter",
"Gallente Freighter",
"Minmatar Freighter",
"Caldari Dreadnought",
"Gallente Dreadnought",
"Minmatar Dreadnought",
"Capital Ships",
"Exhumers",
"Recon Ships",
"Command Ships",
"Amarr Carrier",
"Caldari Carrier",
"Gallente Carrier",
"Minmatar Carrier",
"Capital Industrial Ships",
"Heavy Interdiction Cruisers",
"Electronic Attack Ships",
"Black Ops",
"Marauders",
"Jump Freighters",
"Industrial Command Ships",
"Amarr Strategic Cruiser",
"Caldari Strategic Cruiser",
"Gallente Strategic Cruiser",
"Minmatar Strategic Cruiser",
"Mining Frigate",
"Amarr Destroyer",
"Caldari Destroyer",
"Gallente Destroyer",
"Minmatar Destroyer",
"Amarr Battlecruiser",
"Caldari Battlecruiser",
"Gallente Battlecruiser",
"Minmatar Battlecruiser",
"Expedition Frigates",
"ORE Freighter",
"Amarr Tactical Destroyer",
"Minmatar Tactical Destroyer",
"Caldari Tactical Destroyer",
"Gallente Tactical Destroyer",
"Command Destroyers",
"Logistics Frigates",
"Flag Cruisers",
"Precursor Frigate",
"Precursor Cruiser",
"Precursor Battleship",
"Precursor Destroyer",
"Precursor Battlecruiser",
"Precursor Dreadnought",
"Leadership",
"Skirmish Command",
"Shield Command",
"Wing Command",
"Armored Command",
"Information Command",
"Mining Foreman",
"Mining Director",
"Fleet Command",
"Fleet Formations",
"Fleet Coordination",
"Fleet Compression Logistics",
"Corporation Management",
"Diplomatic Relations",
"Megacorp Management",
"Empire Control",
"Sovereignty",
"Industry",
"Mass Production",
"Advanced Industry",
"Supply Chain Management",
"Advanced Mass Production",
"Drug Manufacturing",
"Jury Rigging",
"Armor Rigging",
"Astronautics Rigging",
"Drones Rigging",
"Projectile Weapon Rigging",
"Energy Weapon Rigging",
"Hybrid Weapon Rigging",
"Launcher Rigging",
"Shield Rigging",
"Science",
"Research",
"Laboratory Operation",
"Metallurgy",
"High Energy Physics",
"Plasma Physics",
"Nanite Engineering",
"Hydromagnetic Physics",
"Amarr Starship Engineering",
"Minmatar Starship Engineering",
"Graviton Physics",
"Laser Physics",
"Electromagnetic Physics",
"Rocket Science",
"Gallente Starship Engineering",
"Nuclear Physics",
"Mechanical Engineering",
"Electronic Engineering",
"Caldari Starship Engineering",
"Quantum Physics",
"Astronautic Engineering",
"Molecular Engineering",
"Research Project Management",
"Talocan Technology",
"Sleeper Technology",
"Takmahl Technology",
"Yan Jung Technology",
"Scientific Networking",
"Advanced Laboratory Operation",
"Electronic Warfare",
"Sensor Linking",
"Weapon Disruption",
"Propulsion Jamming",
"Signature Masking",
"Cloaking",
"Long Distance Jamming",
"Frequency Modulation",
"Signal Dispersion",
"Signal Suppression",
"Weapon Destabilization",
"Target Painting",
"Signature Focusing",
"Burst Projector Operation",
"Drones",
"Drone Avionics",
"Mining Drone Operation",
"Repair Drone Operation",
"Salvage Drone Operation",
"Heavy Drone Operation",
"Drone Interfacing",
"Drone Navigation",
"Fighters",
"Advanced Drone Avionics",
"Sentry Drone Interfacing",
"Drone Sharpshooting",
"Drone Durability",
"Light Drone Operation",
"Fighter Hangar Management",
"Heavy Fighters",
"Medium Drone Operation",
"Light Fighters",
"Support Fighters",
"Ice Harvesting Drone Operation",
"Trade",
"Retail",
"Broker Relations",
"Visibility",
"Procurement",
"Daytrading",
"Wholesale",
"Advanced Broker Relations",
"Marketing",
"Accounting",
"Tycoon",
"Corporation Contracting",
"Contracting",
"Customs Code Expertise",
"Advanced Contracting",
"Navigation",
"Afterburner",
"Fuel Conservation",
"Acceleration Control",
"Evasive Maneuvering",
"High Speed Maneuvering",
"Warp Drive Operation",
"Jump Drive Operation",
"Micro Jump Drive Operation",
"Cynosural Field Theory",
"Jump Fuel Conservation",
"Jump Drive Calibration",
"Jump Portal Generation",
"Social",
"Negotiation",
"Diplomacy",
"Fast Talk",
"Connections",
"Criminal Connections",
"Mining Connections",
"Distribution Connections",
"Security Connections",
"Shield Operation",
"Shield Management",
"Tactical Shield Manipulation",
"Shield Emission Systems",
"Shield Upgrades",
"Thermal Shield Compensation",
"EM Shield Compensation",
"Kinetic Shield Compensation",
"Explosive Shield Compensation",
"Shield Compensation",
"Invulnerability Core Operation",
"Mechanics",
"Repair Systems",
"Hull Upgrades",
"Remote Armor Repair Systems",
"Capital Repair Systems",
"EM Armor Compensation",
"Explosive Armor Compensation",
"Kinetic Armor Compensation",
"Thermal Armor Compensation",
"Remote Hull Repair Systems",
"Armor Layering",
"Long Range Targeting",
"Target Management",
"Advanced Target Management",
"Signature Analysis",
"Weapon Upgrades",
"Power Grid Management",
"Capacitor Systems Operation",
"Capacitor Management",
"Energy Pulse Weapons",
"Capacitor Emission Systems",
"Energy Grid Upgrades",
"CPU Management",
"Electronics Upgrades",
"Advanced Weapon Upgrades",
"Thermodynamics",
"Nanite Operation",
"Nanite Interfacing",
"Resistance Phasing",
"Astrometrics",
"Survey",
"Archaeology",
"Hacking",
"Astrometric Rangefinding",
"Astrometric Pinpointing",
"Astrometric Acquisition",
"Reprocessing",
"Mining",
"Reprocessing Efficiency",
"Astrogeology",
"Deep Core Mining",
"Mercoxit Ore Processing",
"Scrapmetal Processing",
"Ice Harvesting",
"Ice Processing",
"Mining Upgrades",
"Gas Cloud Harvesting",
"Salvaging",
"Reactions",
"Mass Reactions",
"Advanced Mass Reactions",
"Remote Reactions",
"Rare Moon Ore Processing",
"Industrial Reconfiguration",
"Simple Ore Processing",
"Coherent Ore Processing",
"Variegated Ore Processing",
"Complex Ore Processing",
"Biology",
"Cybernetics",
"Infomorph Psychology",
"Cloning Facility Operation",
"Neurotoxin Recovery",
"Neurotoxin Control",
"Infomorph Synchronizing",
"Advanced Infomorph Psychology",
"Elite Infomorph Psychology",
"Advanced Planetology",
"Planetology",
"Interplanetary Consolidation",
"Command Center Upgrades",
"Remote Sensing",
"Starbase Defense Management",
"Anchoring"
};